# =============================================================================
# CyberToolkit Pro — Data Models
# =============================================================================
# Structured data models used across the entire framework. These provide
# type-safe, serializable containers for tool metadata, execution results,
# security findings, and alert events.
# =============================================================================

from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any, Dict, List, Optional
from datetime import datetime
import json


class Severity(Enum):
    """Standard severity levels for security findings, aligned with CVSS."""
    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ToolCategory(Enum):
    """Canonical tool categories. Modules declare one of these in TOOL_INFO."""
    RECONNAISSANCE = "reconnaissance"
    SCANNING = "scanning"
    WEB = "web"
    EXPLOITATION = "exploitation"
    PASSWORDS = "passwords"
    DETECTION = "detection"
    LOG_ANALYSIS = "log_analysis"
    FORENSICS = "forensics"
    SIEM = "siem"
    REPORTING = "reporting"


@dataclass
class ArgSchema:
    """
    Describes a single argument that a tool accepts.
    Used by the CLI to prompt users and by the API to validate input.
    """
    name: str
    description: str = ""
    arg_type: str = "str"          # str, int, float, bool, file
    required: bool = False
    default: Any = None

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class ToolInfo:
    """
    Rich metadata for a module. Every tool must expose a TOOL_INFO dict
    that can be parsed into this schema.

    Example TOOL_INFO:
        {
            "name": "port_scanner",
            "category": "scanning",
            "description": "Threaded TCP port scanner with banner grabbing",
            "author": "CyberToolkit Pro",
            "version": "1.0.0",
            "args": [
                {"name": "target", "required": True, "description": "Target IP/hostname"},
                {"name": "ports", "default": "1-1024", "description": "Port range"},
            ]
        }
    """
    name: str
    category: str
    description: str = ""
    author: str = "CyberToolkit Pro"
    version: str = "1.0.0"
    args: List[ArgSchema] = field(default_factory=list)
    tags: List[str] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: dict) -> "ToolInfo":
        """Parse a raw TOOL_INFO dict into a validated ToolInfo instance."""
        args = [
            ArgSchema(**a) if isinstance(a, dict) else a
            for a in data.get("args", [])
        ]
        return cls(
            name=data["name"],
            category=data["category"],
            description=data.get("description", ""),
            author=data.get("author", "CyberToolkit Pro"),
            version=data.get("version", "1.0.0"),
            args=args,
            tags=data.get("tags", []),
        )

    def to_dict(self) -> dict:
        d = asdict(self)
        return d


@dataclass
class Finding:
    """
    A single security finding produced by a tool. Findings are collected
    into ToolResult and surfaced in reports.
    """
    title: str
    description: str = ""
    severity: Severity = Severity.INFO
    evidence: str = ""
    remediation: str = ""

    def to_dict(self) -> dict:
        d = asdict(self)
        d["severity"] = self.severity.value
        return d


@dataclass
class ToolResult:
    """
    Structured output from every tool execution. Replaces ad-hoc print
    statements with a serializable, pipeline-friendly result object.
    """
    tool_name: str
    target: str = ""
    status: str = "success"           # success, error, timeout
    data: Dict[str, Any] = field(default_factory=dict)
    findings: List[Finding] = field(default_factory=list)
    stdout: str = ""
    error: str = ""
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    duration_ms: float = 0.0

    def to_dict(self) -> dict:
        d = asdict(self)
        d["findings"] = [f.to_dict() if isinstance(f, Finding) else f for f in self.findings]
        return d

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, default=str)

    @property
    def has_findings(self) -> bool:
        return len(self.findings) > 0

    @property
    def max_severity(self) -> Severity:
        if not self.findings:
            return Severity.INFO
        severity_order = list(Severity)
        return max(
            (f.severity for f in self.findings),
            key=lambda s: severity_order.index(s)
        )


@dataclass
class Alert:
    """Alert event generated by detection/SIEM modules."""
    rule: str
    message: str
    source_ip: str = ""
    severity: Severity = Severity.MEDIUM
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        d = asdict(self)
        d["severity"] = self.severity.value
        return d
